/* ----------------------------------------------
 * Generated by CaesarDeveloper on 2022-6-16 0:57:35
 * For more info contact at: caesararg.dev@gmail.com
 * Licensed under MIT License.
 * Main script to render DC Gaskets webpage.
 * DCGaskets: @init, @i18Loader, @updateContent, @niceSelectInit
 * ---------------------------------------------- */
import "./assets/css/main.css";
import "./assets/css/responsive.css";
import InfoTecnica from "./components/pages/informaciontecnica.js";
import json_en from './assets/i18n/en.json';
import json_es from './assets/i18n/es.json';

import BOLETINES_PDF_1 from "./assets/files/boletines_tecnicos/Cambio_de_sellos_de_valvula.pdf?url";
import BOLETINES_PDF_2 from "./assets/files/boletines_tecnicos/Procedimiento_instalacion_reten.pdf?url";
import BOLETINES_PDF_3 from "./assets/files/boletines_tecnicos/Soluciona_tu_fuga.jpg";

import TABLAS_CONVERSIONES_PDF_1 from "./assets/files/tablas_conversiones/tablas_para_conversiones1.jpg";
import TABLAS_CONVERSIONES_PDF_2 from "./assets/files/tablas_conversiones/tablas_para_conversiones2.jpg";
import TABLAS_CONVERSIONES_PDF_3 from "./assets/files/tablas_conversiones/tablas_para_conversiones3.jpg";

import TABLAS_TECNICAS_PDF_1 from "./assets/files/tablas_tecnicas/tabla_nacional_2022_cv.pdf?url";
import TABLAS_TECNICAS_PDF_2 from "./assets/files/tablas_tecnicas/tabla_americanos_2022_cv.pdf?url";
import TABLAS_TECNICAS_PDF_3 from "./assets/files/tablas_tecnicas/tabla_asiaticas_2022.pdf?url";

import CONSEJOS_TECNICOS_PDF_1 from "./assets/files/consejos_tecnicos/limpieza_de_orificios_roscados.pdf?url";
import CONSEJOS_TECNICOS_PDF_2 from "./assets/files/consejos_tecnicos/tips_y_cuidado_de_los_retenes.pdf?url";



(($) => {

    let i18Jsons = [];

    const DCGaskets = (() => {
        const init = () => {
            const start = new Date();
            const app = new InfoTecnica();            

            try {
                console.log('Iniciando app...');
                i18Jsons.push(json_es);
                i18Jsons.push(json_en);
                document.querySelector('body').classList.add('stop-scrolling');
                document.getElementById("app").insertAdjacentHTML("afterbegin", app.render());                


                let nav = document.querySelector('nav');
                window.addEventListener('scroll', function () {
                    if (window.pageYOffset > 100) {
                        nav.classList.add('bg-dark-transparent', 'shadow');
                    } else {
                        nav.classList.remove('bg-dark-transparent', 'shadow');
                    }
                });

                    
                document.getElementById('btnViewDetailsBoletinesTecnicos').addEventListener('click', function () {
                    $("#modalBoletinesTecnicos").modal("show");
                });

                document.getElementById('btnViewDetailsTablasConversiones').addEventListener('click', function () {
                    $("#modalTablaConversiones").modal("show");
                });

                document.getElementById('btnViewDetailsTablasTecnicas').addEventListener('click', function () {
                    $("#modalTablaTecnica").modal("show");
                });

                document.getElementById('btnViewDetailsConsejosTecnicos').addEventListener('click', function () {
                    $("#modalConsejosTecnicos").modal("show");
                });
                
                

                document.getElementById('btnDescargarBoletines').addEventListener('click', function () {
                    var urls = [BOLETINES_PDF_1, BOLETINES_PDF_2, BOLETINES_PDF_3];
                    downloadFiles(urls)
                });

                document.getElementById('btnDescargarTablasConversiones').addEventListener('click', function () {
                    var urls = [TABLAS_CONVERSIONES_PDF_1, TABLAS_CONVERSIONES_PDF_2, TABLAS_CONVERSIONES_PDF_3];
                    downloadFiles(urls)
                });

                document.getElementById('btnDescargarTablasTecnicas').addEventListener('click', function () {
                    var urls = [TABLAS_TECNICAS_PDF_1, TABLAS_TECNICAS_PDF_2, TABLAS_TECNICAS_PDF_3];
                    downloadFiles(urls)
                });

                document.getElementById('btnDescargarConsejosTecnicos').addEventListener('click', function () {
                    var urls = [CONSEJOS_TECNICOS_PDF_1, CONSEJOS_TECNICOS_PDF_2];
                    downloadFiles(urls)
                });

                document.getElementById('mobileMenuInicio').addEventListener('click', function () {
                    if (document.getElementById("menuToggle").checked) {
                        document.getElementById("menuToggle").checked = false;
                    }
                });

                document.getElementById('mobileMenuEmpresa').addEventListener('click', function () {
                    if (document.getElementById("menuToggle").checked) {
                        document.getElementById("menuToggle").checked = false;
                    }
                });

                document.getElementById('mobileMenuProductos').addEventListener('click', function () {
                    if (document.getElementById("menuToggle").checked) {
                        document.getElementById("menuToggle").checked = false;
                    }
                });

                document.getElementById('mobileMenuContact').addEventListener('click', function () {
                    if (document.getElementById("menuToggle").checked) {
                        document.getElementById("menuToggle").checked = false;
                    }
                });

                
                
            } catch (error) {
                console.error(error);
            } finally {
                console.log('App iniciada...', start.getMilliseconds());
                setTimeout(() => {
                    document.querySelector('body').classList.remove('stop-scrolling');
                }, 3000);
                niceSelectInit();
                i18Loader();                
            }
        }

        const downloadFiles = (urls) => {

            for (const url of urls) {   // here's the for..of statement                
                let a = document.createElement("a");
                a.setAttribute('href', url);
                a.setAttribute('download', '');
                a.setAttribute('target', '_blank');
                a.click();
            }

            if (urls.length == 0) {
                // clearInterval();
            }
        }

        const i18Loader = async () => {

            const langs = ["es", "en"];

            const res = langs.reduce((acc, l, idx) => {
                acc[l] = {
                    translation: i18Jsons[idx]
                };
                return acc;
            }, {});
            await i18next.init({
                lng: "es",
                debug: false,
                resources: res
            });
            updateContent();
            i18next.on("languageChanged", () => {
                updateContent();
            });

            $('.langSelector').on('change', function (e) {
                i18next.changeLanguage(e.target.value);
        
                switch (e.target.value) {
                    case "es":
                        $(".nice-select>.current").prepend('');
                        $(".nice-select>.current").prepend('<i class="flag-icon flag-icon-mx"></i> ');
                        break;

                    case "en":
                        $(".nice-select>.current").prepend('');
                        $(".nice-select>.current").prepend('<i class="flag-icon flag-icon-us"></i> ');
                        break;

                    default:
                        $(".nice-select>.current").prepend('');
                        $(".nice-select>.current").prepend('<i class="flag-icon flag-icon-mx"></i> ');
                        break;
                }

            });
        }

        const updateContent = () => {
            const elements = document.getElementsByClassName("i18nelement");
            for (let i = 0; i < elements.length; i++) {
                const element = elements[i];
                const k = element.getAttribute("data-i18n");
                element.innerHTML = i18next.t(k);
            }
        }

        const niceSelectInit = () => {
            $(".langSelector").niceSelect();
            $(".nice-select>ul.list>li.option[data-value='en']").prepend('<i class="flag-icon flag-icon-us"></i> ');
            $(".nice-select>ul.list>li.option[data-value='es']").prepend('<i class="flag-icon flag-icon-mx"></i> ');
            $(".nice-select>.current").prepend('<i class="flag-icon flag-icon-mx"></i> ');
        }

        return {
            init: init
        };
    })();


    $(document).ready(function () {
        DCGaskets.init();        
    }); 

})(jQuery);